package UserInfo;

import java.util.HashSet;


/**
 * 
 * @author hacheson
 * This is the account class. It is what the home page will call to boot up. It has a user
 * but also has a list of recipes, ingredients, and shopping list.
 */
public class Account {
	private User _user;
	private HashSet<Recipe> _recipes;
	private HashSet<String> _ingredients;
	private HashSet<String> _shoppingList;
	
	public Account(User user, HashSet<Recipe> recipes, HashSet<String> ingredients, HashSet<String> list){
		_user = user;
		_recipes = recipes;
		_ingredients = ingredients;
		//TODO: Will be generated by the api.
		_shoppingList = list;
	}
	
	public Account(User user){
		_user = user;
		_recipes = new HashSet<Recipe>();
		_ingredients = new HashSet<String>();
		_shoppingList = new HashSet<String>();
	}
	
	/**
	 * Returns the user of this account.
	 * @return User The user that this account returns.
	 */
	public User getUser(){
		return _user;
	}
	
	/**
	 * Sets the user of this account.
	 * @param u The user to set.
	 */
	public void setUser(User u){
		_user = u;
	}
	
}
